// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/khaivutri/bookmark-service/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

// CreateUser provides a mock function with given fields: ctx, userName, displayName, password, email
func (_m *MockService) CreateUser(ctx context.Context, userName string, displayName string, password string, email string) (*model.User, error) {
	ret := _m.Called(ctx, userName, displayName, password, email)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 *model.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string) (*model.User, error)); ok {
		return rf(ctx, userName, displayName, password, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string) *model.User); ok {
		r0 = rf(ctx, userName, displayName, password, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, string) error); ok {
		r1 = rf(ctx, userName, displayName, password, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSelfInfo provides a mock function with given fields: ctx, userID
func (_m *MockService) GetSelfInfo(ctx context.Context, userID string) (*model.User, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetSelfInfo")
	}

	var r0 *model.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.User, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.User); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Login provides a mock function with given fields: ctx, userName, password
func (_m *MockService) Login(ctx context.Context, userName string, password string) (string, error) {
	ret := _m.Called(ctx, userName, password)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return rf(ctx, userName, password)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = rf(ctx, userName, password)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, userName, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateSelfInfo provides a mock function with given fields: ctx, userID, displayName, email
func (_m *MockService) UpdateSelfInfo(ctx context.Context, userID string, displayName string, email string) error {
	ret := _m.Called(ctx, userID, displayName, email)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSelfInfo")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, userID, displayName, email)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
