// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/khaivutri/bookmark-service/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// BookmarkRepository is an autogenerated mock type for the BookmarkRepository type
type BookmarkRepository struct {
	mock.Mock
}

// CreateBookmark provides a mock function with given fields: ctx, newBookmark
func (_m *BookmarkRepository) CreateBookmark(ctx context.Context, newBookmark *model.Bookmark) (*model.Bookmark, error) {
	ret := _m.Called(ctx, newBookmark)

	if len(ret) == 0 {
		panic("no return value specified for CreateBookmark")
	}

	var r0 *model.Bookmark
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Bookmark) (*model.Bookmark, error)); ok {
		return rf(ctx, newBookmark)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.Bookmark) *model.Bookmark); ok {
		r0 = rf(ctx, newBookmark)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Bookmark)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.Bookmark) error); ok {
		r1 = rf(ctx, newBookmark)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteBookmarkByID provides a mock function with given fields: ctx, userID, bookmarkID
func (_m *BookmarkRepository) DeleteBookmarkByID(ctx context.Context, userID string, bookmarkID string) error {
	ret := _m.Called(ctx, userID, bookmarkID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteBookmarkByID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, userID, bookmarkID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetBookmarkByCode provides a mock function with given fields: ctx, code
func (_m *BookmarkRepository) GetBookmarkByCode(ctx context.Context, code string) (*model.Bookmark, error) {
	ret := _m.Called(ctx, code)

	if len(ret) == 0 {
		panic("no return value specified for GetBookmarkByCode")
	}

	var r0 *model.Bookmark
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.Bookmark, error)); ok {
		return rf(ctx, code)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.Bookmark); ok {
		r0 = rf(ctx, code)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Bookmark)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, code)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetBookmarkByID provides a mock function with given fields: ctx, id
func (_m *BookmarkRepository) GetBookmarkByID(ctx context.Context, id string) (*model.Bookmark, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetBookmarkByID")
	}

	var r0 *model.Bookmark
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.Bookmark, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.Bookmark); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Bookmark)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetBookmarks provides a mock function with given fields: ctx, userID, limit, offset
func (_m *BookmarkRepository) GetBookmarks(ctx context.Context, userID string, limit int, offset int) ([]*model.Bookmark, int64, error) {
	ret := _m.Called(ctx, userID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetBookmarks")
	}

	var r0 []*model.Bookmark
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) ([]*model.Bookmark, int64, error)); ok {
		return rf(ctx, userID, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) []*model.Bookmark); ok {
		r0 = rf(ctx, userID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Bookmark)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, int) int64); ok {
		r1 = rf(ctx, userID, limit, offset)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, int, int) error); ok {
		r2 = rf(ctx, userID, limit, offset)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// UpdateBookmark provides a mock function with given fields: ctx, userID, bookmarkID, description, url
func (_m *BookmarkRepository) UpdateBookmark(ctx context.Context, userID string, bookmarkID string, description string, url string) error {
	ret := _m.Called(ctx, userID, bookmarkID, description, url)

	if len(ret) == 0 {
		panic("no return value specified for UpdateBookmark")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string) error); ok {
		r0 = rf(ctx, userID, bookmarkID, description, url)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewBookmarkRepository creates a new instance of BookmarkRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBookmarkRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *BookmarkRepository {
	mock := &BookmarkRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
