// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	bookmark "github.com/khaivutri/bookmark-service/internal/service/bookmark"

	mock "github.com/stretchr/testify/mock"

	model "github.com/khaivutri/bookmark-service/internal/model"
)

// BookmarkService is an autogenerated mock type for the BookmarkService type
type BookmarkService struct {
	mock.Mock
}

// AddBookmark provides a mock function with given fields: ctx, description, url, userID
func (_m *BookmarkService) AddBookmark(ctx context.Context, description string, url string, userID string) (*model.Bookmark, error) {
	ret := _m.Called(ctx, description, url, userID)

	if len(ret) == 0 {
		panic("no return value specified for AddBookmark")
	}

	var r0 *model.Bookmark
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (*model.Bookmark, error)); ok {
		return rf(ctx, description, url, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) *model.Bookmark); ok {
		r0 = rf(ctx, description, url, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Bookmark)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, description, url, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteBookmark provides a mock function with given fields: ctx, bookmarkID
func (_m *BookmarkService) DeleteBookmark(ctx context.Context, bookmarkID string) error {
	ret := _m.Called(ctx, bookmarkID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteBookmark")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, bookmarkID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetBookmarks provides a mock function with given fields: ctx, userID, page, limit
func (_m *BookmarkService) GetBookmarks(ctx context.Context, userID string, page int, limit int) (*bookmark.GetBookmarkResponse, error) {
	ret := _m.Called(ctx, userID, page, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetBookmarks")
	}

	var r0 *bookmark.GetBookmarkResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) (*bookmark.GetBookmarkResponse, error)); ok {
		return rf(ctx, userID, page, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) *bookmark.GetBookmarkResponse); ok {
		r0 = rf(ctx, userID, page, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bookmark.GetBookmarkResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, int) error); ok {
		r1 = rf(ctx, userID, page, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateBookmark provides a mock function with given fields: ctx, bookmarkID, description, url
func (_m *BookmarkService) UpdateBookmark(ctx context.Context, bookmarkID string, description string, url string) error {
	ret := _m.Called(ctx, bookmarkID, description, url)

	if len(ret) == 0 {
		panic("no return value specified for UpdateBookmark")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, bookmarkID, description, url)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewBookmarkService creates a new instance of BookmarkService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBookmarkService(t interface {
	mock.TestingT
	Cleanup(func())
}) *BookmarkService {
	mock := &BookmarkService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
