// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/khaivutri/bookmark-service/internal/model"
	bookmark "github.com/khaivutri/bookmark-service/internal/service/bookmark"
	mock "github.com/stretchr/testify/mock"
)

// BookmarkService is an autogenerated mock type for the BookmarkService type
type BookmarkService struct {
	mock.Mock
}

// AddBookmark provides a mock function with given fields: ctx, descriptio, url, userID
func (_m *BookmarkService) AddBookmark(ctx context.Context, descriptio string, url string, userID string) (*model.Bookmark, error) {
	ret := _m.Called(ctx, descriptio, url, userID)

	if len(ret) == 0 {
		panic("no return value specified for AddBookmark")
	}

	var r0 *model.Bookmark
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (*model.Bookmark, error)); ok {
		return rf(ctx, descriptio, url, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) *model.Bookmark); ok {
		r0 = rf(ctx, descriptio, url, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Bookmark)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, descriptio, url, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetBookmarks provides a mock function with given fields: ctx, userID, page, limit
func (_m *BookmarkService) GetBookmarks(ctx context.Context, userID string, page int, limit int) (*bookmark.GetBookmarkResponse, error) {
	ret := _m.Called(ctx, userID, page, limit)

	var r0 *bookmark.GetBookmarkResponse
	var r1 error
	if ret.Get(0) != nil {
		r0 = ret.Get(0).(*bookmark.GetBookmarkResponse)
	}
	r1 = ret.Error(1)

	return r0, r1
}

// NewBookmarkService creates a new instance of BookmarkService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBookmarkService(t interface {
	mock.TestingT
	Cleanup(func())
}) *BookmarkService {
	mock := &BookmarkService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
